
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Dec 13 17:37:34 EST 2015
//----------------------------------------------------

package ic.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CBRACE = 19;
  public static final int MULT = 30;
  public static final int GE = 40;
  public static final int SEMI = 23;
  public static final int CONTINUE = 15;
  public static final int INT = 11;
  public static final int LIBRARY = 32;
  public static final int MINUS = 29;
  public static final int OBRACE = 18;
  public static final int CLS_ID = 44;
  public static final int OBRACKET = 24;
  public static final int NOT = 36;
  public static final int AND = 34;
  public static final int LT = 37;
  public static final int CBRACKET = 25;
  public static final int OR = 35;
  public static final int COMMA = 22;
  public static final int CLASS = 2;
  public static final int DIV = 31;
  public static final int PLUS = 28;
  public static final int IF = 5;
  public static final int THIS = 4;
  public static final int ID = 43;
  public static final int DOT = 27;
  public static final int LE = 38;
  public static final int EOF = 0;
  public static final int BOOLEAN = 12;
  public static final int RETURN = 3;
  public static final int CPAREN = 21;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int EQEQ = 41;
  public static final int NULL = 17;
  public static final int MOD = 33;
  public static final int BREAK = 14;
  public static final int VOID = 8;
  public static final int EQ = 26;
  public static final int ELSE = 9;
  public static final int OPAREN = 20;
  public static final int WHILE = 16;
  public static final int NE = 42;
  public static final int EXTENDS = 6;
  public static final int BOOL_LIT = 47;
  public static final int STRING = 13;
  public static final int STRING_LIT = 45;
  public static final int INT_LIT = 46;
  public static final int GT = 39;
  public static final int LENGTH = 10;
}

